DATA:
  HE_FEATURE_ROOT: 'xxx/xxx/xx/TCGA-LUNG-Feature-Path'
  IHC_FEATURE_ROOT: 'xxx/xxx/xx/TCGA-LUNG-Feature-Path'
  HE_TRAIN_VALID_CSV: './data/TCGA-LUNG/TCGA_LUNG_trainval.csv'
  IHC_TRAIN_VALID_CSV: './data/TCGA-LUNG/TCGA_LUNG_trainval.csv'
  HE_TEST_CSV: './data/TCGA-LUNG/TCGA_LUNG_test.csv'
  IHC_TEST_CSV: './data/TCGA-LUNG/TCGA_LUNG_test.csv'

MODEL:
  FEATURE_DIM: 512
  NUM_CLASS: 4
  SELECT_K: 100
  KL_WEIGHT: 1
  RETURN_ATTE: False

TRAIN:
  IS_SAME_CASE: False
  MAX_EPOCH: 100
  BATCH_SIZE: 1
  WORKERS: 12
  LR: 0.0002
  WEIGHT_DECAY: 0.00001
  WEIGHTS_SAVE_PATH: './save'
